name: Deploy Employee Portfolio Infra

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip contact form Lambda function
        run: |
          mkdir -p lambda_zips
          zip -j lambda_zips/contact_handler.zip lambda/contact_handler.py

      - name: Zip visitor logger Lambda function
        run: |
          zip -j lambda_zips/visitor_logger.zip lambda/visitor_logger.py

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Export Terraform outputs to environment
        id: api
        run: |
          cd terraform
          echo "API_URL=$(terraform output -raw analytics_api_url)" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV


      - name: Upload static website to S3
        run: |
          aws s3 sync frontend/ s3://$S3_BUCKET_NAME --delete

      
      - name: Print API URL (for debugging)
        run: echo "API Gateway URL is $API_URL"

